import {
    Card,
    List,
    ListItem,
    ListItemPrefix,
    Typography,
    Radio,
} from "@material-tailwind/react";

export function CheckboxHorizontalListGroup() {
    return (
        <Card
            className="w-full max-w-[28rem] bg-div"
            placeholder
            onPointerEnterCapture
            onPointerLeaveCapture
        >
            <List
                className="flex-row"
                placeholder
                onPointerEnterCapture
                onPointerLeaveCapture
            >
                <ListItem
                    className="p-0"
                    placeholder
                    onPointerEnterCapture
                    onPointerLeaveCapture
                >
                    <label
                        htmlFor="horizontal-list-react"
                        className="flex w-full cursor-pointer items-center px-3 py-2"
                    >
                        <ListItemPrefix
                            className="mr-3"
                            placeholder
                            onPointerEnterCapture
                            onPointerLeaveCapture
                        >
                            <Radio
                                id="horizontal-list-visa"
                                name="payment-method"
                                ripple={false}
                                containerProps={{
                                    className: "p-0",
                                }}
                                onPointerEnterCapture
                                onPointerLeaveCapture
                                crossOrigin
                            />
                        </ListItemPrefix>
                        <Typography
                            color="blue-gray"
                            className="font-medium"
                            placeholder
                            onPointerEnterCapture
                            onPointerLeaveCapture
                        >
                            Visa
                        </Typography>
                    </label>
                </ListItem>
                <ListItem
                    className="p-0"
                    placeholder
                    onPointerEnterCapture
                    onPointerLeaveCapture
                >
                    <label
                        htmlFor="horizontal-list-vue"
                        className="flex w-full cursor-pointer items-center px-3 py-2"
                    >
                        <ListItemPrefix
                            className="mr-3"
                            placeholder
                            onPointerEnterCapture
                            onPointerLeaveCapture
                        >
                            <Radio
                                id="horizontal-list-mastercard"
                                name="payment-method"
                                ripple={false}
                                containerProps={{
                                    className: "p-0",
                                }}
                                onPointerEnterCapture
                                onPointerLeaveCapture
                                crossOrigin
                            />
                        </ListItemPrefix>
                        <Typography
                            color="blue-gray"
                            className="font-medium"
                            placeholder
                            onPointerEnterCapture
                            onPointerLeaveCapture
                        >
                            Mastercard
                        </Typography>
                    </label>
                </ListItem>
                <ListItem
                    className="p-0"
                    placeholder
                    onPointerEnterCapture
                    onPointerLeaveCapture
                >
                    <label
                        htmlFor="horizontal-list-svelte"
                        className="flex w-full cursor-pointer items-center px-3 py-2"
                    >
                        <ListItemPrefix
                            className="mr-3"
                            placeholder
                            onPointerEnterCapture
                            onPointerLeaveCapture
                        >
                            <Radio
                                id="horizontal-list-transfer"
                                name="payment-method"
                                ripple={false}
                                containerProps={{
                                    className: "p-0",
                                }}
                                onPointerEnterCapture
                                onPointerLeaveCapture
                                crossOrigin
                            />
                        </ListItemPrefix>
                        <Typography
                            color="blue-gray"
                            className="font-medium"
                            placeholder
                            onPointerEnterCapture
                            onPointerLeaveCapture
                        >
                            Transferencia
                        </Typography>
                    </label>
                </ListItem>
            </List>
        </Card>
    );
}